name: Update README

on:
  push:
    branches:
      - '*'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List branches in README.md
        run: |
          echo "# My Project Branches" > README.md
          echo "" >> README.md
          echo "## Branches disponíveis:" >> README.md
          git branch -r | sed 's/origin\///g' >> README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Atualizando lista de branches"
          git push

